[package]
name = "evj-media"
edition.workspace = true
version.workspace = true

[features]
ffmpeg = ["dep:ffmpeg-next"]

[dependencies]
anyhow.workspace = true
snap.workspace = true
ffmpeg-next = { version = "9", optional = true }
windows = { workspace = true, features = [
  "Win32_Foundation", "Win32_Graphics_Direct3D11", "Win32_Graphics_Dxgi_Common",
  "Win32_Media_MediaFoundation", "Win32_System_Com", "Win32_System_Com_StructuredStorage", "Win32_System_Variant",
  "Win32_Graphics_Imaging",
] }

[dev-dependencies]
evj-render = { path = "../evj-render" }
